import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import PageHeader from '../components/PageHeader'
import InsightCard from '../components/InsightCard'
import StatCard from '../components/StatCard'
import { useAppStore } from '../store/useAppStore'
import { cycleLengths, formatDate, getStats, periodDuration, sortOldest } from '../utils/cycleCalculations'
export default function Insights() {
  const { logs, settings } = useAppStore(), stats = getStats(logs, settings), sorted = sortOldest(logs), cycles = cycleLengths(logs)
  const trends = sorted.map((log, index) => ({ name: formatDate(log.startDate, 'MMM'), cycle: index ? cycles[index - 1] : null, duration: periodDuration(log), pain: log.painLevel }))
  const counts = {}; logs.flatMap((log) => log.symptoms || []).forEach((item) => { counts[item] = (counts[item] || 0) + 1 }); const symptomData = Object.entries(counts).map(([name, count]) => ({ name, count })).sort((a,b) => b.count-a.count)
  const flows = {}; logs.forEach((log) => { if (log.flow) flows[log.flow] = (flows[log.flow] || 0) + 1 }); const commonFlow = Object.entries(flows).sort((a,b) => b[1]-a[1])[0]?.[0] || 'More data needed'
  return <section className="page"><PageHeader title="Insights" subtitle="Patterns from the data you choose to log" back/><div className="stats-grid"><StatCard label="Average cycle" value={`${stats.averageCycleLength} days`}/><StatCard label="Average period" value={`${stats.averagePeriodDuration} days`}/><StatCard label="Shortest / longest" value={stats.shortest ? `${stats.shortest} / ${stats.longest} days` : 'More data needed'}/><StatCard label="Regularity score" value={stats.regularityScore === null ? 'More data needed' : `${stats.regularityScore}/100`} detail={stats.regularity}/><StatCard label="Fertile confidence" value={stats.fertileConfidence.label} detail={stats.fertileConfidence.detail}/><StatCard label="Predicted PMS" value={formatDate(stats.pmsStart, 'MMM d')} detail={stats.pmsEnd ? `to ${formatDate(stats.pmsEnd, 'MMM d')}` : ''}/></div><InsightCard title="Cycle length trend">{!cycles.length ? <ChartEmpty/> : <ResponsiveContainer width="100%" height={210}><LineChart data={trends}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis domain={['dataMin - 2','dataMax + 2']}/><Tooltip/><Line type="monotone" dataKey="cycle" stroke="#2D7D7A" strokeWidth={3}/></LineChart></ResponsiveContainer>}</InsightCard><InsightCard title="Period duration trend"><ResponsiveContainer width="100%" height={210}><BarChart data={trends}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="duration" fill="#7EC4CF" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></InsightCard><InsightCard title="Symptoms frequency">{!symptomData.length ? <ChartEmpty/> : <ResponsiveContainer width="100%" height={220}><BarChart data={symptomData} layout="vertical"><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={78}/><Tooltip/><Bar dataKey="count" fill="#2D7D7A" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer>}</InsightCard><div className="card prose"><h3>At a glance</h3><p><strong>Flow pattern:</strong> {commonFlow}</p><p><strong>Pain trend:</strong> {logs.some((l) => l.painLevel !== null) ? `Average ${Math.round(logs.filter(l => l.painLevel !== null).reduce((s,l) => s+l.painLevel,0)/logs.filter(l => l.painLevel !== null).length)}/10` : 'More data needed'}</p></div></section>
}
function ChartEmpty() { return <div className="chart-empty"><span>✦</span><strong>More history needed</strong><p>Log more periods to reveal this pattern.</p></div> }
