import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Modal from '../components/Modal'
import PageHeader from '../components/PageHeader'
import PinInput from '../components/PinInput'
import { useAppStore } from '../store/useAppStore'
export default function Settings() {
  const { logs, settings, changePin, resetAll, lock } = useAppStore(), navigate = useNavigate()
  const [pinOpen, setPinOpen] = useState(false), [pin, setPin] = useState(''), [confirmPin, setConfirmPin] = useState(''), [resetOpen, setResetOpen] = useState(false), [resetText, setResetText] = useState(''), [message, setMessage] = useState('')
  const exportData = () => { const safeSettings = { ...settings }; delete safeSettings.pinHash; const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), settings: safeSettings, periodLogs: logs }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `tempo-export-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href) }
  const savePin = async () => { if (pin.length !== 4 || pin !== confirmPin) return setMessage('PINs must match and contain four digits.'); await changePin(pin); setPinOpen(false); setPin(''); setConfirmPin(''); setMessage('PIN updated.') }
  return <section className="page"><PageHeader title="Settings" subtitle="Privacy and app preferences"/>{message && <p className="notice">{message}</p>}<section className="card settings-list"><button onClick={() => setPinOpen(true)}><span><strong>Change PIN</strong><small>Update your local privacy lock</small></span><b>›</b></button><button onClick={exportData}><span><strong>Export data</strong><small>Download your logs as JSON</small></span><b>›</b></button><button onClick={() => { lock(); navigate('/unlock') }}><span><strong>Lock now</strong><small>TEMPO also locks after 5 minutes inactive</small></span><b>›</b></button><button className="danger-text" onClick={() => setResetOpen(true)}><span><strong>Reset all data</strong><small>Permanently erase this device’s TEMPO data</small></span><b>›</b></button></section><section className="card prose"><h3>Private by design</h3><p>TEMPO stores your data only on this device in this version. Predictions are estimates and should not be used as medical advice or contraception guidance.</p><p className="muted">Version 1.0.0</p></section><Modal open={pinOpen} title="Change PIN" onClose={() => setPinOpen(false)}><label>New PIN<PinInput value={pin} onChange={setPin} autoFocus={false}/></label><label>Confirm new PIN<PinInput value={confirmPin} onChange={setConfirmPin} autoFocus={false}/></label>{message && <p className="error">{message}</p>}<div className="modal-actions"><button className="button secondary" onClick={() => setPinOpen(false)}>Cancel</button><button className="button primary" onClick={savePin}>Save PIN</button></div></Modal><Modal open={resetOpen} title="Reset TEMPO?" onClose={() => setResetOpen(false)}><p>All saved data till now will be lost. This cannot be undone.</p><label>Type RESET to continue<input value={resetText} onChange={(e) => setResetText(e.target.value)}/></label><div className="modal-actions"><button className="button secondary" onClick={() => setResetOpen(false)}>Cancel</button><button className="button danger" disabled={resetText !== 'RESET'} onClick={async () => { await resetAll(); navigate('/') }}>Reset all data</button></div></Modal></section>
}
